### ISSUE TITLE
Attempts to update CiviCRM to use Smarty v5 fail with this plugin enabled

### ISSUE THREAD

**Issue by mikesafh** [MillerTech-CRM/uk.co.nfpservices.module.memberonlyevent#16]
Trying to enable Smarty v5 in CiviCRM with this plugin enabled gives me the following (PHP 8.1.0, planning on updating to 8.3 next weekend):

[20-Oct-2024 13:22:54 UTC] PHP Fatal error:  Uncaught Error: Cannot access protected property Smarty\Smarty::$template_dir in /var/www/html/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php:37
Stack trace:
#0 /var/www/html/wp-content/uploads/civicrm/ext/uk.co.nfpservices.module.memberonlyevent-master/memberonlyevent.civix.php(22): Smarty->__get()
#1 /var/www/html/wp-content/uploads/civicrm/ext/uk.co.nfpservices.module.memberonlyevent-master/memberonlyevent.php(11): _memberonlyevent_civix_civicrm_config()
#2 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(276): memberonlyevent_civicrm_config()
#3 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(136): CRM_Utils_Hook->runHooks()
#4 /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(314): CRM_Utils_Hook_WordPress->invokeViaUF()
#5 /var/www/html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Civi\Core\CiviEventDispatcher::delegateToUF()
#6 /var/www/html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#7 /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(263): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#8 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(168): Civi\Core\CiviEventDispatcher->dispatch()
#9 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(1492): CRM_Utils_Hook->invoke()
#10 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Config.php(100): CRM_Utils_Hook::config()
#11 /var/www/html/wp-content/plugins/civicrm/includes/civicrm.admin.php(444): CRM_Core_Config::singleton()
#12 /var/www/html/wp-content/plugins/civicrm/civicrm.php(1002): CiviCRM_For_WordPress_Admin->initialize()
#13 /var/www/html/wp-content/plugins/civicrm/includes/civicrm.functions.php(101): CiviCRM_For_WordPress->initialize()
#14 /var/www/html/wp-content/plugins/civievent-widget/civievent-widget.php(182): civicrm_initialize()
#15 /var/www/html/wp-content/plugins/civievent-widget/civievent-widget.php(174): civievent_Widget->commonConstruct()
#16 /var/www/html/wp-includes/class-wp-widget-factory.php(62): civievent_Widget->__construct()
#17 /var/www/html/wp-includes/widgets.php(123): WP_Widget_Factory->register()
#18 /var/www/html/wp-content/plugins/civievent-widget/civievent-widget.php(32): register_widget()
#19 /var/www/html/wp-includes/class-wp-hook.php(324): {closure}()
#20 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#21 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#22 /var/www/html/wp-includes/widgets.php(1870): do_action()
#23 /var/www/html/wp-includes/class-wp-hook.php(324): wp_widgets_init()
#24 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#25 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#26 /var/www/html/wp-settings.php(700): do_action()
#27 /var/www/html/wp-config.php(137): require_once('...')
#28 /var/www/html/wp-load.php(50): require_once('...')
#29 /var/www/html/wp-admin/admin.php(34): require_once('...')
#30 /var/www/html/wp-admin/index.php(10): require_once('...')
#31 {main}
  thrown in /var/www/html/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php on line 37

I think this may just require re-running civix, but am not sure if that's something that can be done on the extension files or with the files that build the extension (relatively new to that level of extension debugging).

Michael

**Comment by shaneonabike** [comment]
This is no longer being maintained you should start using https://civicrm.org/extensions/member-only-event
